// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go
//
// Generated by this command:
//
//	mockgen -package mock -source=contract.go -destination=../mock/repository.go *
//

// Package mock is a generated GoMock package.
package mock

import (
	context "context"
	domain "coupon_be/domain"
	util "coupon_be/util"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
	isgomock struct{}
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// CreateCoupon mocks base method.
func (m *MockRepository) CreateCoupon(ctx context.Context, data *domain.Coupon) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateCoupon", ctx, data)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateCoupon indicates an expected call of CreateCoupon.
func (mr *MockRepositoryMockRecorder) CreateCoupon(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateCoupon", reflect.TypeOf((*MockRepository)(nil).CreateCoupon), ctx, data)
}

// CreateUser mocks base method.
func (m *MockRepository) CreateUser(ctx context.Context, data *domain.User) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, data)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockRepositoryMockRecorder) CreateUser(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockRepository)(nil).CreateUser), ctx, data)
}

// CreateUserClaim mocks base method.
func (m *MockRepository) CreateUserClaim(ctx context.Context, data *domain.UserClaim) (*domain.UserClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUserClaim", ctx, data)
	ret0, _ := ret[0].(*domain.UserClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUserClaim indicates an expected call of CreateUserClaim.
func (mr *MockRepositoryMockRecorder) CreateUserClaim(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUserClaim", reflect.TypeOf((*MockRepository)(nil).CreateUserClaim), ctx, data)
}

// DecrementCouponRemainingAmount mocks base method.
func (m *MockRepository) DecrementCouponRemainingAmount(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecrementCouponRemainingAmount", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DecrementCouponRemainingAmount indicates an expected call of DecrementCouponRemainingAmount.
func (mr *MockRepositoryMockRecorder) DecrementCouponRemainingAmount(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecrementCouponRemainingAmount", reflect.TypeOf((*MockRepository)(nil).DecrementCouponRemainingAmount), ctx, id)
}

// FindCountUserClaimByCouponID mocks base method.
func (m *MockRepository) FindUserClaimCountByCouponID(ctx context.Context, couponID uint64) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserClaimCountByCouponID", ctx, couponID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCountUserClaimByCouponID indicates an expected call of FindCountUserClaimByCouponID.
func (mr *MockRepositoryMockRecorder) FindCountUserClaimByCouponID(ctx, couponID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserClaimCountByCouponID", reflect.TypeOf((*MockRepository)(nil).FindUserClaimCountByCouponID), ctx, couponID)
}

// FindCouponByID mocks base method.
func (m *MockRepository) FindCouponByID(ctx context.Context, id uint64) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCouponByID", ctx, id)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCouponByID indicates an expected call of FindCouponByID.
func (mr *MockRepositoryMockRecorder) FindCouponByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCouponByID", reflect.TypeOf((*MockRepository)(nil).FindCouponByID), ctx, id)
}

// FindCouponByName mocks base method.
func (m *MockRepository) FindCouponByName(ctx context.Context, name string, withClaimBy bool) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCouponByName", ctx, name, withClaimBy)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCouponByName indicates an expected call of FindCouponByName.
func (mr *MockRepositoryMockRecorder) FindCouponByName(ctx, name, withClaimBy any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCouponByName", reflect.TypeOf((*MockRepository)(nil).FindCouponByName), ctx, name, withClaimBy)
}

// FindCouponsPaginated mocks base method.
func (m *MockRepository) FindCouponsPaginated(ctx context.Context, search string, p *util.Pagination) ([]*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindCouponsPaginated", ctx, search, p)
	ret0, _ := ret[0].([]*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindCouponsPaginated indicates an expected call of FindCouponsPaginated.
func (mr *MockRepositoryMockRecorder) FindCouponsPaginated(ctx, search, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindCouponsPaginated", reflect.TypeOf((*MockRepository)(nil).FindCouponsPaginated), ctx, search, p)
}

// FindUserByID mocks base method.
func (m *MockRepository) FindUserByID(ctx context.Context, id uint64) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByID", ctx, id)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByID indicates an expected call of FindUserByID.
func (mr *MockRepositoryMockRecorder) FindUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByID", reflect.TypeOf((*MockRepository)(nil).FindUserByID), ctx, id)
}

// FindUserByUsername mocks base method.
func (m *MockRepository) FindUserByUsername(ctx context.Context, username string) (*domain.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserByUsername", ctx, username)
	ret0, _ := ret[0].(*domain.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserByUsername indicates an expected call of FindUserByUsername.
func (mr *MockRepositoryMockRecorder) FindUserByUsername(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserByUsername", reflect.TypeOf((*MockRepository)(nil).FindUserByUsername), ctx, username)
}

// FindUserClaimByUserIDAndCouponID mocks base method.
func (m *MockRepository) FindUserClaimByUserIDAndCouponID(ctx context.Context, userID, couponID uint64) (*domain.UserClaim, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindUserClaimByUserIDAndCouponID", ctx, userID, couponID)
	ret0, _ := ret[0].(*domain.UserClaim)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindUserClaimByUserIDAndCouponID indicates an expected call of FindUserClaimByUserIDAndCouponID.
func (mr *MockRepositoryMockRecorder) FindUserClaimByUserIDAndCouponID(ctx, userID, couponID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindUserClaimByUserIDAndCouponID", reflect.TypeOf((*MockRepository)(nil).FindUserClaimByUserIDAndCouponID), ctx, userID, couponID)
}

// UpdateCoupon mocks base method.
func (m *MockRepository) UpdateCoupon(ctx context.Context, data *domain.Coupon) (*domain.Coupon, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCoupon", ctx, data)
	ret0, _ := ret[0].(*domain.Coupon)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateCoupon indicates an expected call of UpdateCoupon.
func (mr *MockRepositoryMockRecorder) UpdateCoupon(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCoupon", reflect.TypeOf((*MockRepository)(nil).UpdateCoupon), ctx, data)
}
