// Code generated by MockGen. DO NOT EDIT.
// Source: base.go
//
// Generated by this command:
//
//	mockgen -package service -source=base.go -destination=../../mock/service/comment.go -mock_names Service=MockCommentService *
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	request "coupon_be/request"
	response "coupon_be/response"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockCommentService is a mock of Service interface.
type MockCommentService struct {
	ctrl     *gomock.Controller
	recorder *MockCommentServiceMockRecorder
	isgomock struct{}
}

// MockCommentServiceMockRecorder is the mock recorder for MockCommentService.
type MockCommentServiceMockRecorder struct {
	mock *MockCommentService
}

// NewMockCommentService creates a new mock instance.
func NewMockCommentService(ctrl *gomock.Controller) *MockCommentService {
	mock := &MockCommentService{ctrl: ctrl}
	mock.recorder = &MockCommentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentService) EXPECT() *MockCommentServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockCommentService) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentService)(nil).Delete), ctx, id)
}

// Detail mocks base method.
func (m *MockCommentService) Detail(ctx context.Context, id uint64) (*response.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(*response.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockCommentServiceMockRecorder) Detail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockCommentService)(nil).Detail), ctx, id)
}

// FilterComments mocks base method.
func (m *MockCommentService) FilterComments(ctx context.Context, input *request.FilterComment) (*response.BasePagination[[]*response.Comment], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterComments", ctx, input)
	ret0, _ := ret[0].(*response.BasePagination[[]*response.Comment])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterComments indicates an expected call of FilterComments.
func (mr *MockCommentServiceMockRecorder) FilterComments(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterComments", reflect.TypeOf((*MockCommentService)(nil).FilterComments), ctx, input)
}

// Store mocks base method.
func (m *MockCommentService) Store(ctx context.Context, input *request.CreateComment) (*response.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, input)
	ret0, _ := ret[0].(*response.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockCommentServiceMockRecorder) Store(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockCommentService)(nil).Store), ctx, input)
}

// Update mocks base method.
func (m *MockCommentService) Update(ctx context.Context, input *request.UpdateComment) (*response.Comment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*response.Comment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommentServiceMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommentService)(nil).Update), ctx, input)
}
