// Code generated by MockGen. DO NOT EDIT.
// Source: base.go
//
// Generated by this command:
//
//	mockgen -package service -source=base.go -destination=../../mock/service/post.go -mock_names Service=MockPostService *
//

// Package service is a generated GoMock package.
package service

import (
	enums "base_project/domain/enums"
	request "base_project/request"
	response "base_project/response"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPostService is a mock of Service interface.
type MockPostService struct {
	ctrl     *gomock.Controller
	recorder *MockPostServiceMockRecorder
	isgomock struct{}
}

// MockPostServiceMockRecorder is the mock recorder for MockPostService.
type MockPostServiceMockRecorder struct {
	mock *MockPostService
}

// NewMockPostService creates a new mock instance.
func NewMockPostService(ctrl *gomock.Controller) *MockPostService {
	mock := &MockPostService{ctrl: ctrl}
	mock.recorder = &MockPostServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostService) EXPECT() *MockPostServiceMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockPostService) Delete(ctx context.Context, id uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockPostServiceMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockPostService)(nil).Delete), ctx, id)
}

// Detail mocks base method.
func (m *MockPostService) Detail(ctx context.Context, id uint64) (*response.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Detail", ctx, id)
	ret0, _ := ret[0].(*response.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Detail indicates an expected call of Detail.
func (mr *MockPostServiceMockRecorder) Detail(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Detail", reflect.TypeOf((*MockPostService)(nil).Detail), ctx, id)
}

// FilterMyPosts mocks base method.
func (m *MockPostService) FilterMyPosts(ctx context.Context, input *request.FilterPost) (*response.BasePagination[[]*response.Post], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterMyPosts", ctx, input)
	ret0, _ := ret[0].(*response.BasePagination[[]*response.Post])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterMyPosts indicates an expected call of FilterMyPosts.
func (mr *MockPostServiceMockRecorder) FilterMyPosts(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterMyPosts", reflect.TypeOf((*MockPostService)(nil).FilterMyPosts), ctx, input)
}

// FilterPosts mocks base method.
func (m *MockPostService) FilterPosts(ctx context.Context, input *request.FilterPost) (*response.BasePagination[[]*response.Post], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FilterPosts", ctx, input)
	ret0, _ := ret[0].(*response.BasePagination[[]*response.Post])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FilterPosts indicates an expected call of FilterPosts.
func (mr *MockPostServiceMockRecorder) FilterPosts(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FilterPosts", reflect.TypeOf((*MockPostService)(nil).FilterPosts), ctx, input)
}

// Store mocks base method.
func (m *MockPostService) Store(ctx context.Context, input *request.UpsertPost) (*response.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, input)
	ret0, _ := ret[0].(*response.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Store indicates an expected call of Store.
func (mr *MockPostServiceMockRecorder) Store(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockPostService)(nil).Store), ctx, input)
}

// Update mocks base method.
func (m *MockPostService) Update(ctx context.Context, input *request.UpsertPost) (*response.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, input)
	ret0, _ := ret[0].(*response.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockPostServiceMockRecorder) Update(ctx, input any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockPostService)(nil).Update), ctx, input)
}

// UpdateStatus mocks base method.
func (m *MockPostService) UpdateStatus(ctx context.Context, id uint64, status enums.PostStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockPostServiceMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockPostService)(nil).UpdateStatus), ctx, id, status)
}
