--
-- PostgreSQL database dump
--

\restrict 5gn0Hnh4dc8iAONwfVEOxfq4TeJo0e2MSJpA3AFNLmIETqfi8YjZNQ1cG2y3ZFb

-- Dumped from database version 14.7 (Debian 14.7-1.pgdg110+1)
-- Dumped by pg_dump version 14.20

-- Started on 2026-01-12 06:32:27 UTC

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3362 (class 1262 OID 16384)
-- Name: coupon_db; Type: DATABASE; Schema: -; Owner: admin
--

CREATE DATABASE coupon_db WITH TEMPLATE = template0 ENCODING = 'UTF8' LOCALE = 'en_US.utf8';


ALTER DATABASE coupon_db OWNER TO admin;

\unrestrict 5gn0Hnh4dc8iAONwfVEOxfq4TeJo0e2MSJpA3AFNLmIETqfi8YjZNQ1cG2y3ZFb
\connect coupon_db
\restrict 5gn0Hnh4dc8iAONwfVEOxfq4TeJo0e2MSJpA3AFNLmIETqfi8YjZNQ1cG2y3ZFb

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 3 (class 2615 OID 2200)
-- Name: public; Type: SCHEMA; Schema: -; Owner: admin
--

CREATE SCHEMA public;


ALTER SCHEMA public OWNER TO admin;

--
-- TOC entry 3363 (class 0 OID 0)
-- Dependencies: 3
-- Name: SCHEMA public; Type: COMMENT; Schema: -; Owner: admin
--

COMMENT ON SCHEMA public IS 'standard public schema';


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 214 (class 1259 OID 16462)
-- Name: coupons; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.coupons (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    name character varying(255) NOT NULL,
    amount integer NOT NULL,
    remaining_amount integer NOT NULL,
    CONSTRAINT amount_must_be_positive CHECK ((amount >= 0)),
    CONSTRAINT remaining_amount_must_be_positive CHECK ((remaining_amount >= 0))
);


ALTER TABLE public.coupons OWNER TO admin;

--
-- TOC entry 213 (class 1259 OID 16461)
-- Name: coupons_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.coupons_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.coupons_id_seq OWNER TO admin;

--
-- TOC entry 3364 (class 0 OID 0)
-- Dependencies: 213
-- Name: coupons_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.coupons_id_seq OWNED BY public.coupons.id;


--
-- TOC entry 210 (class 1259 OID 16441)
-- Name: goose_db_version; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.goose_db_version (
    id integer NOT NULL,
    version_id bigint NOT NULL,
    is_applied boolean NOT NULL,
    tstamp timestamp without time zone DEFAULT now() NOT NULL
);


ALTER TABLE public.goose_db_version OWNER TO admin;

--
-- TOC entry 209 (class 1259 OID 16440)
-- Name: goose_db_version_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

ALTER TABLE public.goose_db_version ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.goose_db_version_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 16474)
-- Name: user_claims; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.user_claims (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    user_id bigint NOT NULL,
    coupon_id bigint NOT NULL
);


ALTER TABLE public.user_claims OWNER TO admin;

--
-- TOC entry 215 (class 1259 OID 16473)
-- Name: user_claims_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.user_claims_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.user_claims_id_seq OWNER TO admin;

--
-- TOC entry 3365 (class 0 OID 0)
-- Dependencies: 215
-- Name: user_claims_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.user_claims_id_seq OWNED BY public.user_claims.id;


--
-- TOC entry 212 (class 1259 OID 16448)
-- Name: users; Type: TABLE; Schema: public; Owner: admin
--

CREATE TABLE public.users (
    id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at timestamp without time zone,
    username character varying(100) NOT NULL,
    password text NOT NULL,
    full_name character varying(255)
);


ALTER TABLE public.users OWNER TO admin;

--
-- TOC entry 211 (class 1259 OID 16447)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: admin
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.users_id_seq OWNER TO admin;

--
-- TOC entry 3366 (class 0 OID 0)
-- Dependencies: 211
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: admin
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- TOC entry 3186 (class 2604 OID 16465)
-- Name: coupons id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.coupons ALTER COLUMN id SET DEFAULT nextval('public.coupons_id_seq'::regclass);


--
-- TOC entry 3191 (class 2604 OID 16477)
-- Name: user_claims id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_claims ALTER COLUMN id SET DEFAULT nextval('public.user_claims_id_seq'::regclass);


--
-- TOC entry 3183 (class 2604 OID 16451)
-- Name: users id; Type: DEFAULT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- TOC entry 3354 (class 0 OID 16462)
-- Dependencies: 214
-- Data for Name: coupons; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.coupons (id, created_at, updated_at, deleted_at, name, amount, remaining_amount) VALUES (1, '2026-01-12 13:30:26.478027', '2026-01-12 13:30:26.478027', NULL, 'COUPON_TEST', 10, 10);


--
-- TOC entry 3350 (class 0 OID 16441)
-- Dependencies: 210
-- Data for Name: goose_db_version; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.goose_db_version (id, version_id, is_applied, tstamp) VALUES (1, 0, true, '2026-01-12 06:29:58.464946');
INSERT INTO public.goose_db_version (id, version_id, is_applied, tstamp) VALUES (2, 20251201080611, true, '2026-01-12 06:29:58.490336');
INSERT INTO public.goose_db_version (id, version_id, is_applied, tstamp) VALUES (3, 20260108071722, true, '2026-01-12 06:29:58.501692');


--
-- TOC entry 3356 (class 0 OID 16474)
-- Dependencies: 216
-- Data for Name: user_claims; Type: TABLE DATA; Schema: public; Owner: admin
--



--
-- TOC entry 3352 (class 0 OID 16448)
-- Dependencies: 212
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: admin
--

INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (1, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_0', '$2a$10$V2BaTCHBtcjOcHeStK.LiOaf1IMWR.IC2qiloR0CDHO0q/31TFqVG', 'User 0');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (2, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_1', '$2a$10$BqZPAXCy2yuHSJ84yGtFGu6ICKsIoJs3L3IkL2gUJr8pjERCyFose', 'User 1');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (3, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_2', '$2a$10$Z/U8PfFs55RHMwLrqZmz0OMx2gJljCbm/WQElFCM4pGKH4k8VYdyW', 'User 2');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (4, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_3', '$2a$10$XPLqFEFlAadXvM06iEHXyuRLuV9sKgfXTuvIz1ANWqVblP.eA68uC', 'User 3');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (5, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_4', '$2a$10$lVXUwwEL0Wd9F1vU9zgnlOCVAvu1wSWoUzUGwSH7PeIS9XorFEJkq', 'User 4');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (6, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_5', '$2a$10$C1ch3HMOQkwZKw/UHsiiyuUJzmcg45qvWtPsgrDVwibOdrLAokDMm', 'User 5');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (7, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_6', '$2a$10$lO0srFTq9tHAuIiBnOMxS.aS4lKFHUGKcDtCiW6q3jvo2WlMZQUy6', 'User 6');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (8, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_7', '$2a$10$gTWHD6DNr3Nqii7eWFvHqOp2Or3CMCc8rlS5KgmSRp.2Ba2v1EvLW', 'User 7');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (9, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_8', '$2a$10$.EkRCzXmBqtPvNDuksZxVue6yuFma1RsrC65FHOYoe7SPRnYQbM9q', 'User 8');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (10, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_9', '$2a$10$htuZbyRAnS0/s90l8DnCV.FgXCT4V6EfFij.g/wirf5N7XnNIU1zW', 'User 9');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (11, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_10', '$2a$10$pej9XlI4GE.GT9WWTp9sf.H27gNCP4qZagkp0FA4ysJrQfPQuwStW', 'User 10');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (12, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_11', '$2a$10$AFuEMAJq70lkdIFkBsD/1uquvfEQcwmOAdK0yLdT59UsGeQV7569W', 'User 11');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (13, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_12', '$2a$10$E.AA38BW32b/WjbUPpamK.NManwTtT.IfJAnOMLSj2h8PVACJNGKC', 'User 12');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (14, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_13', '$2a$10$JCB9GmY8jdoyd9./zkVogeHhWR2ox.fq7Zu2SjilpPMUNph0H/Dom', 'User 13');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (15, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_14', '$2a$10$j/jNZLGcIFrX7vvYDMbz/Oam9H/zcZWMUm1gqRcJh.V7I7cwiHfES', 'User 14');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (16, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_15', '$2a$10$OqUujmoQ0viAWi2461VlE.8shCX5Gk1JrsHMkZiITR26U3QhQleuC', 'User 15');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (17, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_16', '$2a$10$I9klKhPD4KtrITJVxhl8b.xfWLtZ/l50U.pTlaBac561/AlL3KQC6', 'User 16');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (18, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_17', '$2a$10$5QSJEnKo08cJGre5rYq0tenlRm6TLSTaN4jzZTD7SBPKlQigVZI9S', 'User 17');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (19, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_18', '$2a$10$lHnVes4ppio6XVvzCOID.uN9yVSYYS56KrwLumfKim4FdSyw28kQm', 'User 18');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (20, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_19', '$2a$10$zMkWo9NtcAScjEMRX/K84.zdjjsHnNdK1j/NM.m32gMoPugQGywPS', 'User 19');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (21, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_20', '$2a$10$5kOr3fVrFroOpbujUXA.DO4izTOokrG7hPwM6ROy7uz.c5S4XXL1m', 'User 20');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (22, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_21', '$2a$10$4ljcPL4HMlbeLDhl7nb.rO/GiHu6Z1SSaH.l4DIB6bhcGbJf39tlm', 'User 21');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (23, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_22', '$2a$10$ePzxOYb1ALIwKBqN/DwiF.9T2Ur2obJZSg21V0TaemedrRBSgN3OW', 'User 22');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (24, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_23', '$2a$10$AL53mp2MmiMAej.27NqAHeJy.lrq.MBL6Xlx68k/boHImkBFOb4gq', 'User 23');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (25, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_24', '$2a$10$LK5fZTP.i.eyGW5byaVzJ.xxXrEKTWh5qk0NylxJ0ygAWvPCpbufy', 'User 24');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (26, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_25', '$2a$10$VviEU8LyRiFQWPZ9BTc.9.HIBEmtTYu8c0yuAtPdVJzJVVGdTdlXe', 'User 25');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (27, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_26', '$2a$10$fWk.bdJs0GParWVZrlbggOFOwjIi7p3LYvM//eTQesXuCgklyH6aa', 'User 26');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (28, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_27', '$2a$10$Q.vf6tOqoNjfAde5j8Rwce28d.dpnGiR2FCVL0Zfs.UFrvokWNk.m', 'User 27');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (29, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_28', '$2a$10$WWPw1ajVvxFdAQSY3MhlAO2fZtM8XClMHm0gxKoBCMab3H8g7oTzC', 'User 28');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (30, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_29', '$2a$10$e4bLgo2U78Osygyv0KiRxelcJzUcMTe3AeOPRsrYTnPEYMrxD8Kyy', 'User 29');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (31, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_30', '$2a$10$qEYHGttVuaGyfTKBw0/OVu4hq2xDdqeAr5oA9wNX41nPZm1T9f7AK', 'User 30');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (32, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_31', '$2a$10$N8pS/btDerv.BYUN8n/v5.EFS6If10rNQjUb/C40TPXdfzmuxw9Uy', 'User 31');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (33, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_32', '$2a$10$hsf4M0zBXQDol4IOYiyaUucme9b/fvnlM6UwrcoeSNLgrBwmhWaZW', 'User 32');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (34, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_33', '$2a$10$.bfLzAA4LG2I6bua.W4Hkeuq1rM6VJ5wyMSLDkvYJV1FTvX0CDtvK', 'User 33');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (35, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_34', '$2a$10$IWbSyJqZujQofucWlvK46OJWmcdXz3Tuh4nLx.K3A6s/Zo197OBc.', 'User 34');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (36, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_35', '$2a$10$MJZvOd2TjmbHyqQmx132GeE.cyHMqPiXSWmzKoe7r12NulIPOBd76', 'User 35');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (37, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_36', '$2a$10$GzLtN399ZJfFs9LbtClD9.q81A3K8n6At/1bJc.xebI8mYg5GXJCi', 'User 36');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (38, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_37', '$2a$10$v.bJgpNPCphbMmKgPb/zBeFckNsNVG5TUXdzwwkE0bXgIMQDM6jm6', 'User 37');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (39, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_38', '$2a$10$2xB9/xWn82g40gM1vz8KLO/L91Cw3WxKr0LxjGjmbjFvNRDWPkQ3y', 'User 38');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (40, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_39', '$2a$10$mHcn6N2pxVFosJB/72trOuW1MqapHoEG4ZhlWeYYbkLBbxFd25U9a', 'User 39');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (41, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_40', '$2a$10$FlE0krzG5AQSOwE/ddbkMuMqBO4JH3g/D//V//IwTgkowsVY2VpS2', 'User 40');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (42, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_41', '$2a$10$r4KNrwrqRyCKI3T4rb3eWOYzkE55Z67NzBL8QCHW7hMCqrTOeAi.W', 'User 41');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (43, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_42', '$2a$10$keymnZE4tsxbJ4iMHgZOcOIkxyuj7t4lBEyVCC35xr05ZYFbtebtO', 'User 42');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (44, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_43', '$2a$10$aKBy4d1/0/4qpPqQ2bEARepmUR3ZId01V2hBIW.TfFMrWopOYl/fS', 'User 43');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (45, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_44', '$2a$10$pThRmXXq5Uy73ZwvQYhZE.wHVrcsBmXecCVcdh2OjK81.2CRo8kJS', 'User 44');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (46, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_45', '$2a$10$B8pbmwDM64.K0Sp3k7mGl.ehXFjUqSlDE85B30megR2BRQ7AsW9r.', 'User 45');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (47, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_46', '$2a$10$79Lzgl3crkiFk5JTpufG2ej2xGTAf3Rc1J1oG17nSzPtTFiJFDPnm', 'User 46');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (48, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_47', '$2a$10$s3SRDhRKbR7MPRA4wFKu/exNWdJCIi07HOoltbJpqTiQ5cPcESTmG', 'User 47');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (49, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_48', '$2a$10$bnMg9UfMzmG03HjY3CQT2eiDye9QGbt4SXGKEk2eKaNMNlTXO8jpe', 'User 48');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (50, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_49', '$2a$10$BE.rxhv0aq0D.IYiC3EiqO5hPDfaoUyQaFUQLrGUriE26Pacx31z.', 'User 49');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (51, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_50', '$2a$10$RM54lTZVvPjkE2xz1DmKGe4.5.Fqiiy7M728Gj5FwhV6vX2xD/z/.', 'User 50');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (52, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_51', '$2a$10$zGY5I3W4N8IbtlxvDOqHAu8bEtfo5zkzzEsVHc.IKN3lMXD8KlJqG', 'User 51');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (53, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_52', '$2a$10$LceAuoJEeIJ9HYhIulxZTupi.9GHoFE8nviDB7WyGMPTwJksleqxm', 'User 52');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (54, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_53', '$2a$10$/zjrBXbkYNGqEyOf/LnEFOO2sE2/KcHQ05bLMKez4vfv0TJZkltze', 'User 53');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (55, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_54', '$2a$10$YqKjYHn2OiUfyi8KAcb2tu1TcVkVA5AnbNp7JkuTLQLWkbOQnq9di', 'User 54');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (56, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_55', '$2a$10$bGqh6CELJ/NJwVxICr9zNOnQzgyDOkTlwBH3Xs9Nmtvghqwp69oji', 'User 55');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (57, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_56', '$2a$10$9E40RrYejPcYMWfYyhj2UeoOoz2FbPcW3lcEbyr74b6L373d/XCfG', 'User 56');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (58, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_57', '$2a$10$8g03b3if./smFTII/4VrfesM7lRodGgiP9CkvS2AdmVzm4/PhDKTq', 'User 57');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (59, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_58', '$2a$10$cs388mrCSwqvOXVzNyS4KeOtldcOAw.NJgPRqrtLFAst5c5B.IDqG', 'User 58');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (60, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_59', '$2a$10$5qASpHPXE2uI0Uh.GOhZE.QnEgAigtIGjzF53h0QP9Q4MPo0K47Wi', 'User 59');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (61, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_60', '$2a$10$P/icPYKBQfZEuzyDN9Sige63/1BOariBM5seOPDET3UG8uHXSWWcm', 'User 60');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (62, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_61', '$2a$10$vREG0KqyI30w/8F8TrdmbedA/PLZLWnVfzgJJWgkV8Y7n5Sd7WndK', 'User 61');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (63, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_62', '$2a$10$B.my2t193tuhsBalI1/g3OuhY4VwcCR28sQ3ZumFdANCtjju.R6aq', 'User 62');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (64, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_63', '$2a$10$qG6Q8uMw4RkkibHlxymmZ.18VeST5bPk0pmhaJZOWOr5wz45WZem6', 'User 63');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (65, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_64', '$2a$10$.DOKXWPJXYbtQ9zSvvAm4eAdEcmLDcU0ylN7uV6KJiYZjNMVK.bcy', 'User 64');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (66, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_65', '$2a$10$3YJXIQcC.tLvI/Rm.ekheuc37r767cHdKIjqTPn9VGH2S/Sm6R3J6', 'User 65');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (67, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_66', '$2a$10$QaH9.cBm.JF41KXvn8c/2.GQHRQWjjpga5r4hqLq4nfFTh43RmEEe', 'User 66');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (68, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_67', '$2a$10$CS4/PbelbYTL3aF2Ba.wgeWWHf3QffIaZQT8qHUhRhNy0Hao4A9Zi', 'User 67');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (69, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_68', '$2a$10$zCK.m77Z9KAoT9UxULTSPuRFLHfSILeSFrVa8NEBC08rBjWsuo/ru', 'User 68');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (70, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_69', '$2a$10$bTg4r2gp5qXQbLavahRv4OlW1HrzFg0C8gO1PwdqeMXMMYyaEJA4y', 'User 69');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (71, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_70', '$2a$10$kNzgNDYmHGyEUTC5Zvr3G.np9AipSOW4zaQD75SKt.1bVRG9rx4NS', 'User 70');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (72, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_71', '$2a$10$JFZGCZU0z9..8VgxFdt/lu5GbPuvZPDb/ZXJ105XEAj0wVk5lJBhu', 'User 71');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (73, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_72', '$2a$10$9bJStipgbZlhy78bNmiXo.oJKMx.PZGtbINHMmzKP5qa0WdnpCWtS', 'User 72');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (74, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_73', '$2a$10$LwPg477Ck2VDdQQibGnvouPta686TH534Hnyba2PU7wiJxJzyu/Zy', 'User 73');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (75, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_74', '$2a$10$QOBRdOag/r0N3EwZY9adAOJzU1Te.qkqO8.mUV6xYrKnSvs/cDHLW', 'User 74');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (76, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_75', '$2a$10$Du9NmGq2.uZAHFgmoFI0yOnGWCq1hxdva7pbWr0mtlhn6KNZlRXHm', 'User 75');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (77, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_76', '$2a$10$JtL.Wz5ITxi.pjeN5R3IAOtVsOWBN2yilh/vOWYzMuspeNua.ZDDe', 'User 76');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (78, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_77', '$2a$10$NErXbtBAXH7uuIe1Avn4D.Kf2q67imTCU9cmJFXnIFUog2ISbDvl6', 'User 77');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (79, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_78', '$2a$10$vj5BiNEPG5KhP/JyvKXoXOtOkGQY03OWxA9q12U.fTzSA.NlEQ07a', 'User 78');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (80, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_79', '$2a$10$V5SLW3V3NWO/VDAVMHU2pemVRKiaiy13fY.mTvWjqYr0d.6qPinia', 'User 79');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (81, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_80', '$2a$10$jUk2MPTCuQFcnbAKxQtUNuvtb3bPMn9K8DyAcMVmegbZWsvvq.igK', 'User 80');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (82, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_81', '$2a$10$z9UGDBoWi3sjxOmNoyaZ3.V/5AOxBudcwp9Qu.xQa1NCeoVJlkp9a', 'User 81');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (83, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_82', '$2a$10$I2CTIci9Tt2xoXYv.EBZsOiskVQZAt73IGXmToCiAwNRDqbhPGACG', 'User 82');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (84, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_83', '$2a$10$KZQYjMbLxGSWdlK7BjFDcuRQwgvwePR6tS69BRrnmrWyg8babNtbu', 'User 83');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (85, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_84', '$2a$10$XzeIAIluAmKc2cxx.f.g6.tpg4w6uBTQJe4vDi5dXIawpE4PjTdru', 'User 84');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (86, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_85', '$2a$10$P2uXmyqWISpl9ivXHEuKX.P92wNa4Xqn4OJN5yyZ0b1fWm4fKJ.CK', 'User 85');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (87, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_86', '$2a$10$Q24dV6Vi8SQf2brsQA/h4OjF/OSzTrkXkdIzbL1SQatqHdAlbePtS', 'User 86');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (88, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_87', '$2a$10$k2E3d9HSqY2mHmYp4gorM.Ln/rwh8txyAVVEPkWT7Hk8Apr6f8py6', 'User 87');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (89, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_88', '$2a$10$9udBaw9m1FK51Oucg20QN.jbOc2QrDzcBJEEj3dZqVIjm5UBQdjq.', 'User 88');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (90, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_89', '$2a$10$odyN60nOxGs8l64UVy49sernu6MBAlxt3PRjd/21YPGZbNVmfpQZK', 'User 89');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (91, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_90', '$2a$10$7pFSUTeqrVYddfYhadlIWO20IXc3CNTYXAKNIMJIWCSGu1JJv5YLC', 'User 90');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (92, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_91', '$2a$10$hwqCHwLj6F4Mj7m4wVooR.2pAGQFFoQHf5xri5LgJmamVfK0PjaNm', 'User 91');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (93, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_92', '$2a$10$e2lcYrjXPFt1rU5xSpl.u.YHSc7SWsHQj4fShklPRenA9YOUlu7dq', 'User 92');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (94, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_93', '$2a$10$mZ0jZjhm7HEjWC8NRMs2GuY71HKdDT1QMl7EvtceCIKwoSXcWmUJW', 'User 93');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (95, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_94', '$2a$10$CneuHg9s9AG8mB0XWeA.9OJJDFIvWJ3YJWdYDn37xRzI087MS56Jm', 'User 94');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (96, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_95', '$2a$10$RbnEe4fJ0OkqEkbrQLVmA.C8zLNEZLtLLTxVjpWD6fSx9MQe/N0N.', 'User 95');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (97, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_96', '$2a$10$KDpsv5wjQ69ZZp7aCZ6e/eA5HT2YdrtiR7Qo7FdMIHbBOR7R8TK/i', 'User 96');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (98, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_97', '$2a$10$Y2HOLeW44k1A0fXhF3/dS.OBLmgn3GoBWgMiFoyaFboBTthDMHjoK', 'User 97');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (99, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_98', '$2a$10$qayQxpf1K592r.FLIcwKSuJYANZTPwF..ZjdxJsrxlLsMQSPWe5c2', 'User 98');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (100, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_99', '$2a$10$rVj/11saunIXPaUsUZz03Oq0ELYBQ6XkB/WWjffpDTES22V3fWPZm', 'User 99');
INSERT INTO public.users (id, created_at, updated_at, deleted_at, username, password, full_name) VALUES (101, '2026-01-12 13:30:16.389582', '2026-01-12 13:30:16.389582', NULL, 'user_100', '$2a$10$NRcX6wpJZR.zTRvfzoPkj.oa.wSYWhdr2PkCI1cNj2/F7oR1BZPUW', 'User 100');


--
-- TOC entry 3367 (class 0 OID 0)
-- Dependencies: 213
-- Name: coupons_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.coupons_id_seq', 1, true);


--
-- TOC entry 3368 (class 0 OID 0)
-- Dependencies: 209
-- Name: goose_db_version_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.goose_db_version_id_seq', 3, true);


--
-- TOC entry 3369 (class 0 OID 0)
-- Dependencies: 215
-- Name: user_claims_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.user_claims_id_seq', 1, false);


--
-- TOC entry 3370 (class 0 OID 0)
-- Dependencies: 211
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: admin
--

SELECT pg_catalog.setval('public.users_id_seq', 101, true);


--
-- TOC entry 3203 (class 2606 OID 16471)
-- Name: coupons coupons_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.coupons
    ADD CONSTRAINT coupons_pkey PRIMARY KEY (id);


--
-- TOC entry 3195 (class 2606 OID 16446)
-- Name: goose_db_version goose_db_version_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.goose_db_version
    ADD CONSTRAINT goose_db_version_pkey PRIMARY KEY (id);


--
-- TOC entry 3205 (class 2606 OID 16481)
-- Name: user_claims user_claims_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_claims
    ADD CONSTRAINT user_claims_pkey PRIMARY KEY (id);


--
-- TOC entry 3207 (class 2606 OID 16483)
-- Name: user_claims user_claims_user_id_coupon_id_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_claims
    ADD CONSTRAINT user_claims_user_id_coupon_id_key UNIQUE (user_id, coupon_id);


--
-- TOC entry 3198 (class 2606 OID 16457)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 3200 (class 2606 OID 16459)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 3201 (class 1259 OID 16472)
-- Name: coupon_name_unique_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX coupon_name_unique_idx ON public.coupons USING btree (name) WHERE (deleted_at IS NULL);


--
-- TOC entry 3196 (class 1259 OID 16460)
-- Name: username_unique_idx; Type: INDEX; Schema: public; Owner: admin
--

CREATE UNIQUE INDEX username_unique_idx ON public.users USING btree (username) WHERE (deleted_at IS NULL);


--
-- TOC entry 3209 (class 2606 OID 16489)
-- Name: user_claims user_claims_coupon_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_claims
    ADD CONSTRAINT user_claims_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id);


--
-- TOC entry 3208 (class 2606 OID 16484)
-- Name: user_claims user_claims_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: admin
--

ALTER TABLE ONLY public.user_claims
    ADD CONSTRAINT user_claims_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id);


-- Completed on 2026-01-12 06:32:27 UTC

--
-- PostgreSQL database dump complete
--

\unrestrict 5gn0Hnh4dc8iAONwfVEOxfq4TeJo0e2MSJpA3AFNLmIETqfi8YjZNQ1cG2y3ZFb

